-- CondoHub (Supabase Postgres) — Minimal seed (optional)
-- Creates: 1 plan, 1 instance, 1 condo profile, 1 block, 1 unit, 1 sindico admin, 1 morador, 2 staff.
-- NOTE: You MUST replace password hashes with real hashes generated by your backend.

begin;

insert into public.plans (id, name, features, limits)
values (gen_random_uuid(), 'MVP', '{}'::jsonb, '{}'::jsonb)
returning id;

-- Replace with your own fixed UUIDs if you want reproducible seeds
with p as (
  select id as plan_id from public.plans where name='MVP' order by created_at desc limit 1
),
i as (
  insert into public.instances (instance_key, name, status, plan_id)
  select 'demo', 'Condo Demo', 'ACTIVE', p.plan_id from p
  returning id as instance_id
),
cp as (
  insert into public.condo_profile (instance_id, display_name)
  select instance_id, 'Condo Demo' from i
  returning instance_id
),
b as (
  insert into public.blocks (instance_id, label)
  select instance_id, 'Bloco A' from i
  returning id as block_id, instance_id
),
u as (
  insert into public.units (instance_id, block_id, label)
  select instance_id, block_id, 'A-101' from b
  returning id as unit_id, instance_id
)
insert into public.users (instance_id, unit_id, name, email, password_hash, roles)
select
  u.instance_id,
  null,
  'Síndico Admin',
  'sindico@demo.com',
  '$2b$10$REPLACE_WITH_REAL_HASH',
  array['SINDICO_ADMIN']::text[]
from u;

with u as (
  select instance_id, unit_id from public.units where label='A-101' order by created_at desc limit 1
)
insert into public.users (instance_id, unit_id, name, email, password_hash, roles)
select
  u.instance_id,
  u.unit_id,
  'Morador Demo',
  'morador@demo.com',
  '$2b$10$REPLACE_WITH_REAL_HASH',
  array['MORADOR']::text[]
from u;

with inst as (
  select id as instance_id from public.instances where instance_key='demo' order by created_at desc limit 1
)
insert into public.users (instance_id, unit_id, name, email, password_hash, roles)
select instance_id, null, 'Entregas Demo', 'entregas@demo.com', '$2b$10$REPLACE_WITH_REAL_HASH', array['FUNC_ENTREGAS']::text[]
from inst;

with inst as (
  select id as instance_id from public.instances where instance_key='demo' order by created_at desc limit 1
)
insert into public.users (instance_id, unit_id, name, email, password_hash, roles)
select instance_id, null, 'Manutenção Demo', 'manutencao@demo.com', '$2b$10$REPLACE_WITH_REAL_HASH', array['FUNC_MANUTENCAO']::text[]
from inst;

commit;
